project_name: cron
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64  
nfpms:
- maintainer: Fagner Carvalho <fagnerncarvalho@gmail.com>
  description: Get live flights data from OpenSky API and save in a PostgreSQL database.
  homepage: https://github.com/nearbyflights/cron
  license: MIT
  formats:
  - deb
  - rpm
  - apk
archives:
  - id: cron
    replacements:
      darwin: macos
      386: 32bit
      amd64: 64bit
      arm: arm32
    format_overrides:
      -
        goos: windows
        format: zip
    files:
      - README.md 
release:
  prerelease: auto
  name_template: "{{.Tag}}"   
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch      